name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
    steps:
      - name: Deploy to Development
        run: |
          echo "Deploying to Development Environment"
          # Add your deployment commands here

  deploy-qa:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: qa
    steps:
      - name: Deploy to QA
        run: |
          echo "Deploying to QA Environment"
          # Add your deployment commands here

  deploy-test:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: test
    steps:
      - name: Deploy to Test
        run: |
          echo "Deploying to Test Environment"
          # Add your deployment commands here

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: prod
    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying to Production Environment"
          # Add your deployment commands here